import test from 'node:test';
import assert from 'node:assert/strict';
import {createStorage} from '../src/storage.js';
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function environment(){const saved=new Map(),events={};globalThis.localStorage={getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v)};globalThis.window={addEventListener:(n,f)=>events[n]=f};globalThis.document={activeElement:null};Object.defineProperty(globalThis,'navigator',{value:{onLine:true},configurable:true});return{saved,events};}
function hooks(){const statuses=[];return{statuses,onState:()=>{},onStatus:s=>statuses.push(s),toast:()=>{},dialog:()=>{},esc:String,exportData:()=>{}};}
function mockClient({rows=[],rpc}={}){return {auth:{onAuthStateChange:()=>{},getSession:async()=>({data:{session:{user:{id:'user-a',email:'test@example.invalid'}}}})},from:()=>({select:()=>({eq:async()=>({data:rows,error:null})})}),rpc:rpc??(async()=>({data:1,error:null}))};}
test('local changes survive adapter reinitialization',async()=>{environment();const a=await createStorage(hooks(),{url:'',key:''});const state={days:{'2026-09-24':{shift:'Guardia'}},weeks:{},measurements:[]};a.save('days','2026-09-24',state.days['2026-09-24'],state);const b=await createStorage(hooks(),{url:'',key:''});assert.equal(b.state.days['2026-09-24'].shift,'Guardia');});
test('cloud loads personal data and saves the expected version',async()=>{environment();const calls=[];const client=mockClient({rows:[{section:'days',record_key:'2026-09-24',value:{shift:'Normal'},version:3}],rpc:async(_name,args)=>{calls.push(args);return{data:4,error:null};}});const h=hooks(),a=await createStorage(h,{url:'https://example.invalid',key:'public',client});assert.equal(a.state.days['2026-09-24'].shift,'Normal');const next=structuredClone(a.state);next.days['2026-09-24'].shift='Guardia';a.save('days','2026-09-24',next.days['2026-09-24'],next);await tick();assert.equal(calls[0].p_expected_version,3);assert.equal(h.statuses.at(-1),'Guardado en la nube');});
test('offline changes remain pending and retry on reconnection',async()=>{const env=environment();let calls=0;const a=await createStorage(hooks(),{url:'x',key:'p',client:mockClient({rpc:async()=>{calls++;return{data:1,error:null};}})});navigator.onLine=false;const next={days:{'2026-09-24':{done:[true,false,false,false]}},weeks:{},measurements:[]};a.save('days','2026-09-24',next.days['2026-09-24'],next);assert.equal(calls,0);assert.equal(Object.keys(JSON.parse(env.saved.get('mi-ritmo-v1:user-a')).pending).length,1);navigator.onLine=true;env.events.online();await tick();await tick();assert.equal(calls,1);assert.equal(Object.keys(JSON.parse(env.saved.get('mi-ritmo-v1:user-a')).pending).length,0);});
test('version conflicts preserve the unsynced edit and report the issue',async()=>{const env=environment(),h=hooks();const a=await createStorage(h,{url:'x',key:'p',client:mockClient({rpc:async()=>({data:null,error:{message:'VERSION_CONFLICT'}})})});const next={days:{'2026-09-24':{shift:'Guardia nocturna'}},weeks:{},measurements:[]};a.save('days','2026-09-24',next.days['2026-09-24'],next);await tick();assert.match(h.statuses.at(-1),/otro dispositivo/);assert.equal(JSON.parse(env.saved.get('mi-ritmo-v1:user-a')).pending['days:2026-09-24'].value.shift,'Guardia nocturna');});
