import {createClient} from '@supabase/supabase-js';
const empty=()=>({days:{},weeks:{},measurements:[]});
const PREFIX='mi-ritmo-v1:';
export async function createStorage({onState,onStatus,toast,dialog,esc,exportData},testConfig){
 const url=testConfig?.url??import.meta.env?.VITE_SUPABASE_URL,key=testConfig?.key??import.meta.env?.VITE_SUPABASE_PUBLISHABLE_KEY;
 const configured=!!(url&&key);
 const client=configured?(testConfig?.client??createClient(url,key)):null;
 let user=null,namespace='local',state=empty(),pending={},versions={},busy=false,ready=true,issue='';
 function load(){try{const data=JSON.parse(localStorage.getItem(PREFIX+namespace)||'null');state=data?.state??empty();pending=data?.pending??{};versions=data?.versions??{};}catch{state=empty();pending={};versions={};issue='No se pudo leer el guardado local.';}}
 function disk(){try{localStorage.setItem(PREFIX+namespace,JSON.stringify({state,pending,versions}));return true;}catch{issue='No se pudo guardar en el navegador. Descargá un respaldo.';onStatus(issue);return false;}}
 function announce(){onStatus(issue||(user?(Object.keys(pending).length?'Cambios pendientes de sincronizar':'Guardado en la nube'):'Guardado en este navegador'));}
 function hydrate(rows){const next=empty();for(const row of rows){const id=row.section+':'+row.record_key;versions[id]=row.version;if(row.value===null)continue;if(row.section==='measurements')next.measurements.push(row.value);else next[row.section][row.record_key]=row.value;}for(const [id,p] of Object.entries(pending)){if(p.section==='measurements'){next.measurements=next.measurements.filter(r=>r.date!==p.key);if(p.value)next.measurements.push(p.value);}else if(p.value)next[p.section][p.key]=p.value;}state=next;disk();onState(state);}
 async function refresh(){if(!user||busy||!navigator.onLine)return;const uid=user.id;ready=false;const {data,error}=await client.from('diet_records').select('section,record_key,value,version').eq('user_id',uid);if(user?.id!==uid)return;ready=true;if(error){issue='No se pudo conectar con tus datos. Revisá la conexión y la configuración.';announce();return;}issue='';hydrate(data);await flush();announce();}
 async function flush(){if(!user||busy||!ready)return;if(!navigator.onLine){issue='Sin conexión. Cambios guardados en este dispositivo.';announce();return;}busy=true;const uid=user.id;try{for(const [id,entry] of Object.entries(pending)){const snapshot=structuredClone(entry);onStatus('Guardando en la nube…');const {data,error}=await client.rpc('save_diet_record',{p_section:snapshot.section,p_key:snapshot.key,p_value:snapshot.value,p_expected_version:snapshot.version});if(user?.id!==uid)return;if(error){issue=error.message.includes('VERSION_CONFLICT')?'Hay cambios de otro dispositivo. Revisalos en Mi cuenta.':'No se pudo guardar en la nube. Los cambios siguen en este dispositivo.';break;}versions[id]=data;if(pending[id]&&JSON.stringify(pending[id])===JSON.stringify(snapshot))delete pending[id];else if(pending[id])pending[id].version=data;disk();}}catch{issue='No se pudo guardar en la nube. Reintentá desde Mi cuenta.';}finally{busy=false;announce();}if(!issue&&Object.keys(pending).length)void flush();}
 async function switchUser(session){const uid=session?.user?.id??null;if(uid===user?.id)return;user=session?.user??null;namespace=user?user.id:'local';issue='';load();onState(state);if(user){onStatus('Cargando tus datos…');await refresh();}else announce();}
 load();
 const api={get state(){return state;},save(section,recordKey,value,next){state=next;issue='';if(user){const id=section+':'+recordKey;pending[id]={section,key:recordKey,value:structuredClone(value),version:pending[id]?.version??versions[id]??0};}disk();announce();if(user)void flush();},notice(){if(!configured)return '<div class="notice"><span><strong>Modo local.</strong> Tus cambios quedan en este navegador. La nube todavía no está conectada.</span></div>';if(!user)return '<div class="notice"><span><strong>Guardado local.</strong> Entrá a Mi cuenta para guardar y consultar tus datos en otros dispositivos.</span></div>';if(issue||Object.keys(pending).length)return `<div class="notice"><span>${esc(issue||'Hay cambios pendientes. Se sincronizarán al recuperar la conexión.')}</span></div>`;return '';},account(){
  if(!configured){dialog('<h2>Tu espacio personal</h2><p>Por ahora estás usando el guardado de este navegador. El proyecto está preparado para conectar tu cuenta y guardar en la nube.</p><p>Falta completar la conexión con Supabase antes de publicar.</p><div class="dialog-actions"><button class="outline" id="backup">Descargar respaldo</button><button class="primary" data-close>Entendido</button></div>');document.querySelector('#backup').onclick=exportData;return;}
  if(user){const d=dialog(`<h2>Mi cuenta</h2><p class="account-copy">${esc(user.email)}</p><p>${esc(issue||'Tu información está asociada a tu cuenta.')}</p><div class="inline-actions"><button class="outline" id="retry">Actualizar / reintentar</button><button class="outline" id="backup">Descargar respaldo</button></div><p style="margin-top:20px;font-size:.875rem">La prueba local se mantiene separada. Podés copiarla a esta cuenta cuando no haya registros en la nube.</p><button class="text-button" id="import-local">Copiar mi prueba local</button>${issue.includes('otro dispositivo')?'<p>Descargá un respaldo antes de descartar tus cambios pendientes.</p><button class="outline" id="discard">Descartar pendientes y cargar la nube</button>':''}<div class="dialog-actions"><button class="outline" data-close>Cerrar</button><button class="primary" id="signout">Salir</button></div>`);
   d.querySelector('#backup').onclick=exportData;d.querySelector('#retry').onclick=async()=>{d.close();issue='';await refresh();};d.querySelector('#signout').onclick=async()=>{if(busy||Object.keys(pending).length){toast('Sincronizá los cambios pendientes antes de salir.');return;}const {error}=await client.auth.signOut();if(error){toast('No se pudo cerrar la sesión. Reintentá.');return;}d.close();};d.querySelector('#discard')?.addEventListener('click',()=>{d.close();const confirm=dialog('<h2>¿Descartar los pendientes?</h2><p>Se conservarán los datos de la nube. Los cambios sin sincronizar de este navegador se descartarán.</p><div class="dialog-actions"><button class="outline" data-close>Cancelar</button><button class="primary" id="discard-confirm">Descartar</button></div>');confirm.querySelector('#discard-confirm').onclick=async()=>{pending={};disk();confirm.close();await refresh();};});d.querySelector('#import-local').onclick=async()=>{if(!ready||busy){toast('Esperá a que termine la sincronización.');return;}const {data,error}=await client.from('diet_records').select('record_key').eq('user_id',user.id).limit(1);if(error){toast('No se pudo comprobar la cuenta.');return;}if(data.length||Object.keys(pending).length){toast('La cuenta ya tiene registros. La prueba local no se copió.');return;}let local;try{local=JSON.parse(localStorage.getItem(PREFIX+'local')||'null')?.state;}catch{}if(!local){toast('No hay una prueba local para copiar.');return;}for(const section of ['days','weeks'])for(const [key,value]of Object.entries(local[section]||{}))pending[section+':'+key]={section,key,value,version:0};for(const value of local.measurements||[])pending['measurements:'+value.date]={section:'measurements',key:value.date,value,version:0};state=local;disk();onState(state);d.close();await flush();};return;
  }
  const d=dialog('<h2>Entrá a tu cuenta</h2><p>Te enviamos un enlace para entrar, sin contraseña. Abrilo en este mismo navegador.</p><form id="login"><label class="field"><span>Tu correo electrónico</span><input type="email" name="email" autocomplete="email" required placeholder="vos@ejemplo.com"></label><p id="login-message" role="status"></p><div class="dialog-actions"><button type="button" class="outline" data-close>Cancelar</button><button class="primary">Enviar enlace</button></div></form>');d.querySelector('form').onsubmit=async e=>{e.preventDefault();const btn=e.target.querySelector('button.primary');btn.disabled=true;const email=new FormData(e.target).get('email');const {error}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin,shouldCreateUser:true}});d.querySelector('#login-message').textContent=error?'No se pudo enviar el enlace. Revisá el correo e intentá de nuevo.':'Revisá tu correo y la carpeta de spam. El enlace te devuelve a tu plan.';btn.disabled=false;};
 }};
 window.addEventListener('online',()=>{issue='';void refresh();});window.addEventListener('offline',()=>{if(user){issue='Sin conexión. Cambios guardados en este dispositivo.';announce();}});window.addEventListener('focus',()=>{if(user&&!busy&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))void refresh();});
 if(client){client.auth.onAuthStateChange((_event,session)=>{setTimeout(()=>void switchUser(session),0);});const {data,error}=await client.auth.getSession();if(error){issue='No se pudo recuperar la sesión.';}if(data.session)await switchUser(data.session);}
 announce();return api;
}
